### ISSUE TITLE
ArpClient async calls block the thread

### ISSUE THREAD

**Issue by dblsaiko** [OliLay/arp-toolkit-rust#3]
ArpClient::receive_next is marked async, however doesn't contain any await calls and instead calls the blocking ArpClient::next_ethernet_frame. Since send_message_with_check only has receive_next as its only async call and all the other async calls in client.rs are calls to send_message_with_check, all of the methods marked async in ArpClient actually block the thread and async functionality isn't actually used anywhere.

**Comment by OliLay** [comment]
Hi @2xsaiko,
thanks again for finding & reporting this issue . I fixed it in dcb7f27.
Sorry for the long response times, for some reason I did not receive any notifications. 

Maybe you can give feedback to the changes I made. Then I'll publish a new version of the crate.

**Comment by dblsaiko** [comment]
That commit doesn't fix it, since self.rx_channel.next() in next_ethernet_frame is still blocking. I looked into it a little after making this issue and found out it wasn't possible to easily fix this without replacing pnet since it isn't written to support async code.

I ended up writing my own code to send ARP requests along with a small library that replaces pnet (still uses some parts of it though) to create layer 2 sockets, if you want to take a look (however, this uses tokio so it is purely async, and supports Linux only, since that is what I needed): https://git.dblsaiko.net/wolproxy/tree/src/mac.rs and https://git.dblsaiko.net/wolproxy/tree/tokio-layer2/src

If you don't want to replace pnet for the socket though, I suggest removing all the async stuff since it's misleading to have it.

**Comment by jwalton** [comment]
Even getting a interface is going to block the executor I think (although not for very long).

**Comment by OliLay** [comment]
Yes, as stated it's due to `pnet`. 
If I'll have some spare time, I can have a look at replacing `pnet` with something else to access Raw sockets. But I'm not sure when I'll have some spare time to work on this.
Feel free to contribute if you want to.
